GCS_PROJECT_BRANDING = dr
GCS_PROJECT_BRANDING_PREATY = dRonin
GCS_PROJECT_BRANDING_HELP = http://dronin.org
DEFINES += 'GCS_PROJECT_BRANDING=\'\"$$GCS_PROJECT_BRANDING\"\''
DEFINES += 'GCS_PROJECT_BRANDING_PREATY=\'\"$$GCS_PROJECT_BRANDING_PREATY\"\''
DEFINES += 'GCS_PROJECT_BRANDING_HELP=\'\"$$GCS_PROJECT_BRANDING_HELP\"\''
