GCS_PROJECT_BRANDING = dr
GCS_PROJECT_BRANDING_PRETTY = dRonin
GCS_PROJECT_BRANDING_HELP = http://dronin.org
DEFINES += 'GCS_PROJECT_BRANDING=\\\"$$GCS_PROJECT_BRANDING\\\"'
DEFINES += 'GCS_PROJECT_BRANDING_PRETTY=\\\"$$GCS_PROJECT_BRANDING_PRETTY\\\"'
DEFINES += 'GCS_PROJECT_BRANDING_HELP=\\\"$$GCS_PROJECT_BRANDING_HELP\\\"'
