#!/usr/bin/env bash

# Information about dmg generation: http://stackoverflow.com/questions/96882/how-do-i-create-a-nice-looking-dmg-for-mac-os-x-using-command-line-tools

# the following environment variables must be set
: ${ROOT_DIR?} ${BUILD_DIR?} ${PACKAGE_LBL?} ${PACKAGE_DIR?} ${FW_DIR?} ${DMG_LBL?} ${GCS_PACKAGE_DIR}

# more variables
APP_NAME_IN="dRonin-GCS.app"
APP_NAME_OUT="dRonin GCS.app"
APP_PATH="${GCS_PACKAGE_DIR}"
TEMP_FILE="${PACKAGE_DIR}/dRonin-temp.dmg.sparseimage"
OUT_FILE="${PACKAGE_DIR}/${DMG_LBL}.dmg"
ICON_FILE="${ROOT_DIR}/branding/gcs_logo_256.png"
BG_PIC_NAME="osx_package_bg.png"
VOL_NAME="dRonin"

# prepare the stage
rm -f "${TEMP_FILE}"
rm -f "${OUT_FILE}"

hdiutil create -size 500M -type SPARSE -volname "${VOL_NAME}" -fs HFS+ "${TEMP_FILE}"

device=$(hdiutil attach  "${TEMP_FILE}" | \
         egrep '^/dev/' | sed 1q | awk '{print $1}')

# packaging goes here
mkdir "/Volumes/${VOL_NAME}/Firmware"
mkdir "/Volumes/${VOL_NAME}/Utilities"
cp -r "${APP_PATH}/${APP_NAME_IN}" "/Volumes/${VOL_NAME}/${APP_NAME_OUT}"
cp -rp "${FW_DIR}"/* "/Volumes/${VOL_NAME}/Firmware"

mkdir "/Volumes/${VOL_NAME}/.background"

cp "${ROOT_DIR}/branding/${BG_PIC_NAME}" "/Volumes/${VOL_NAME}/.background/"

cp "${BUILD_DIR}/matlab/LogConvert.m" "/Volumes/${VOL_NAME}/Utilities/LogConvert-${PACKAGE_LBL}.m"
cp "${ROOT_DIR}/LICENSE.txt" "/Volumes/${VOL_NAME}"

echo "Changing mounted folder icons"

# Set the icon for the mounted DMG.
# Inspired from http://stackoverflow.com/questions/988920/where-to-find-volume-mount-icon-on-leopard
#cp "${ROOT_DIR}/package/osx/VolumeIcon.icns" "/Volumes/${VOL_NAME}/.VolumeIcon.icns"
#SetFile -a C "/Volumes/${VOL_NAME}"
	
echo "Laying out dmg..."

echo '
   tell application "Finder"
     tell disk "'${VOL_NAME}'"
           open
           set current view of container window to icon view
           set toolbar visible of container window to false
           set statusbar visible of container window to false
           set the bounds of container window to {400, 100, 950, 450}
           set theViewOptions to the icon view options of container window
           set arrangement of theViewOptions to not arranged
           set icon size of theViewOptions to 95
           set background picture of theViewOptions to file ".background:'${BG_PIC_NAME}'"
           make new alias file at container window to POSIX file "/Applications" with properties {name:"Applications"}
           set position of item "'${APP_NAME_OUT}'" of container window to {100, 75}
           set position of item "Applications" of container window to {450, 75}
           set position of item "Firmware" of container window to {100, 260}
           set position of item "Utilities" of container window to {275, 260}
           set position of item "LICENSE.txt" of container window to {450, 260}

           update without registering applications
           delay 5
     end tell
   end tell
' | osascript


chmod -Rf go-w /Volumes/"${VOL_NAME}"
sync

hdiutil detach ${device}

min=`hdiutil resize ${TEMP_FILE} | awk \{print\ \$\1\}`
echo "Resizing dmg to ${min}"

hdiutil resize -sectors ${min} ${TEMP_FILE}
hdiutil convert "${TEMP_FILE}" -format UDBZ -o "${OUT_FILE}"

#Assign the icon to the DMG. Script found here: http://hasseg.org/stuff/assignIconScript/assignIcon.py
"${ROOT_DIR}/package/osx/assignIcon.py" "${ICON_FILE}" "${OUT_FILE}"

# cleanup
rm "${TEMP_FILE}"
