#!/usr/bin/env python

from __future__ import print_function

import argparse
import errno
import code
import struct
import time

# Insert the parent directory into the module import search path.
import os
import sys

sys.path.insert(1, os.path.dirname(sys.path[0]))

from dronin import uavo, telemetry, uavo_collection
from threading import Condition

#-------------------------------------------------------------------------------
USAGE = "%(prog)s"
DESC  = """
  Retrieve the configuration of a flight controller.\
"""

cond = Condition()
pending = []

def completion_cb(obj):
    with cond:
        pending.remove(obj._id)
        cond.notifyAll()

def wait_till_less_than(num):
    with cond:
        while len(pending) > num:
            cond.wait()

#-------------------------------------------------------------------------------
def main():
    tStream = telemetry.get_telemetry_by_args(service_in_iter=False)
    tStream.start_thread()

    settings_objects = tStream.uavo_defs.get_settings_objects()

    tStream.wait_connection()

    remaining = settings_objects[:]

    for s in settings_objects:
        pending.append(s._id)

        tStream.request_object(s, cb=completion_cb)

        wait_till_less_than(5)

    wait_till_less_than(0)

    missing = []
    for s in settings_objects:
        val = tStream.last_values.get(s)
        if val is not None:
            print(val)
        else:
            missing.append(s._name)

    for s in missing:
        print("No instance of %s" % (s))

#-------------------------------------------------------------------------------

if __name__ == "__main__":
    main()
