#!/usr/bin/env python

from __future__ import print_function

import argparse
import errno
import code
import struct
import time

# Insert the parent directory into the module import search path.
import os
import sys

sys.path.insert(1, os.path.dirname(sys.path[0]))

from dronin import uavo, telemetry, uavo_collection

#-------------------------------------------------------------------------------
USAGE = "%(prog)s"
DESC  = """
  Requests/downloads file data.\
"""

#-------------------------------------------------------------------------------
def main():
    tStream = telemetry.get_telemetry_by_args(service_in_iter=False)
    tStream.start_thread()

    tStream.wait_connection()

    sys.stdout.write(tStream.transfer_file(3))

#-------------------------------------------------------------------------------

if __name__ == "__main__":
    main()
