#!/usr/bin/env python

# Proof of concept example of using the logfs api.
from dronin.logfs import LogFSImport

import collections
from xml.etree import ElementTree
from xml.etree.ElementTree import Element, SubElement, Comment, tostring
from xml.dom import minidom

githash='next'
imported = LogFSImport(githash, file('cc3d_settings.bin', 'rb').read())

top = Element('uavobjects')

comment = Comment('Automatically generated by import.py')
top.append(comment)

settings = SubElement(top, 'settings')

for obj_name in sorted(imported.keys()):
    exported_obj = imported[obj_name].to_xml_elem()
    top.append(exported_obj)

def prettify(elem):
    """Return a pretty-printed XML string for the Element.
    """
    rough_string = ElementTree.tostring(elem, 'utf-8')
    reparsed = minidom.parseString(rough_string)
    return reparsed.toprettyxml(indent="  ")

print prettify(top)
